## Numpy

In [2]:
import numpy as np
import os

## Creating Arrays

In [3]:
one_dim_array =  np.array([6,4,2,8,5,9,1])

two_dim_array =  np.array([[6, 4, 2, 8] ,
                           [5, 9, 1, 11]] )
                
 
three_dim_array =  np.array([
    [[56,54,52,58], [55,59,51,556],[57,55,53,52]],
    [[16,14,12,18], [15,19,11,156],[17,15,13,12]]
], dtype='int16')

print(one_dim_array.ndim , one_dim_array.shape)
print(two_dim_array.ndim,  two_dim_array.shape)
print(three_dim_array.ndim,  three_dim_array.shape)

1 (7,)
2 (2, 4)
3 (2, 3, 4)


In [4]:
numbers = np.array([3,2,4,5])
print(numbers)
numbers = np.append(numbers,[6,7])
print(numbers)
numbers = np.insert(numbers,2,8)
print(numbers)

elem = np.where(numbers == 4)
print(elem)
print(numbers[elem])
np.delete(numbers, elem)

[3 2 4 5]
[3 2 4 5 6 7]
[3 2 8 4 5 6 7]
(array([3], dtype=int64),)
[4]


array([3, 2, 8, 5, 6, 7])

In [5]:
print('dtype',three_dim_array.dtype)
print('itemsize',three_dim_array.itemsize)
print('nbytes',three_dim_array.nbytes)


dtype int16
itemsize 2
nbytes 48


## Accessing Changing specific element rows colums etc

In [6]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
# get a specific element
a[1,5]

13

In [8]:
# get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# get specific column
a[:,2]

array([ 3, 10])

In [10]:
#getting little bit more fancey [startindex:endindex:stepsize]

print(a[0,1:6:2])

print(a[0,1:-1:2])

[2 4 6]
[2 4 6]


In [11]:
a[1,5]= 20
a[1,:]

array([ 8,  9, 10, 11, 12, 20, 14])

In [12]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [13]:
print(" ",three_dim_array[0,1,:])

  [ 55  59  51 556]


In [14]:
print("getting first elements of every array of the first array ", three_dim_array[0,:,0])

getting first elements of every array of the first array  [56 55 57]


In [15]:
print("getting first elements of the first array ", three_dim_array[:,0,0])

getting first elements of the first array  [56 16]


### Initialize different type of Arrays

In [16]:
np.zeros([5,2,3])
np.ones([2,4,5])
np.full([2,3,4],89)

array([[[89, 89, 89, 89],
        [89, 89, 89, 89],
        [89, 89, 89, 89]],

       [[89, 89, 89, 89],
        [89, 89, 89, 89],
        [89, 89, 89, 89]]])

In [17]:
print(three_dim_array[:,0,0].mean())


36.0


In [18]:
np.random.rand(4,2,5)

array([[[0.79259902, 0.50523231, 0.75348881, 0.28895936, 0.39690724],
        [0.64704606, 0.47067704, 0.6046669 , 0.48565847, 0.63829753]],

       [[0.79349074, 0.62584193, 0.04144036, 0.70478926, 0.26027786],
        [0.04594121, 0.26035158, 0.22168983, 0.67783523, 0.18197923]],

       [[0.42142521, 0.2223171 , 0.93631486, 0.03932579, 0.59218376],
        [0.96907187, 0.54137367, 0.45391546, 0.14975952, 0.04859074]],

       [[0.01248281, 0.0744904 , 0.7237054 , 0.72016534, 0.09638509],
        [0.05941861, 0.06788479, 0.95119468, 0.73630216, 0.30010528]]])

In [19]:
np.random.randint(-1000,1000, size=[4,2,5])

array([[[ 859,   47, -507, -837, -203],
        [ 563,  256, -809, -435, -809]],

       [[-120, -365,  678,  130, -975],
        [ 463, -349, -143, -718,  -58]],

       [[ 635,  544, -163, -721,  -12],
        [-330,  684,  938,  356, -716]],

       [[ 798, -105,  502, -511,  533],
        [ 311, -996,  125, -783,   23]]])

In [20]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
arr_repeat = np.array([[1,2,3]])
np.repeat(arr_repeat,3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
array_q1=np.full([5,5],1)
array_q1[1:4,1:4]=0
array_q1[2,2]=9
array_q1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [23]:
ar_copy = np.array([1,2,3])
ar_b_copy = ar_copy.copy()
ar_b_copy

array([1, 2, 3])

### Linear Algebra

In [24]:
a = np.full([2,3],2)
b = np.full([3,2],3)
print(a)
print(b)

np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[3 3]
 [3 3]
 [3 3]]


array([[18, 18],
       [18, 18]])

In [25]:
c= np.identity(3)
np.linalg.det(c)

1.0

### READ IT
https://numpy.org/doc/stable/reference/routines.linalg.html

#### Statistics

In [27]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.min(stats,axis=1)

array([1, 4])

In [29]:
np.max(stats)

6

In [33]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorgoninizng Arrays

In [39]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
# Veritcally stacking  vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))

np.hstack([v1,v2])

[[1 2 3 4]
 [5 6 7 8]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
# load data from File

In [57]:
raw_folder = os.path.join(os.path.abspath('..'),'data','raw')
numpyfile_path = os.path.join(raw_folder,'numpy_data.txt', )
filedata = np.genfromtxt(numpyfile_path, delimiter=',')
filedata= filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolen Masking, Advanced Indexing

In [58]:
filedata > 23

array([[False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [59]:
filedata[filedata > 23]

array([196,  75,  34,  42,  33, 766,  75,  55,  33, 999,  78,  76,  88])

In [63]:
aaaa = np.array([1,2,3,4,5,6,7,8,9])
aaaa[[1,2,8]]

array([2, 3, 9])

In [65]:
np.any(filedata > 50, axis =0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [73]:
np.all((filedata > 10) & (filedata < 100),axis = 0)

array([False,  True,  True,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [77]:
q2= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
q2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [79]:
q2[2:4,0:2]

array([[11, 12],
       [16, 17]])